### ISSUE TITLE
bs ant design 

### ISSUE THREAD

**Issue by Enalmada** [zpnester/bs-antd#1]
Hey,

@JakubMarkiewicz just pointed out to me that you are working on a jsx3 version of ant design. 
Are you aware of this project? https://github.com/thangngoc89/bs-ant-design
That project was very limited in scope so I added most of the remaining bindings here in a branch I have yet to merge back in: https://github.com/Enalmada/bs-ant-design

There is a pull request to get it up to jsx3 here: https://github.com/Enalmada/bs-ant-design/pull/2.  In the short term I wanted to call it out incase it helps in any way...though yours looks to be gaining maturity pretty quick.

The author of bs-ant-design just mentioned he is no longer maintaining the project so the existing community there is trying to figure out how to best go forward.  Ideally there would just be one project everyone helps maintain and we can get all the other similar enough projects to point to a single place we can all collaborate.  Do you have any interest in merging your efforts with bs-ant-design/pull/2 and continuing together?

**Comment by zpnester** [comment]
Thanks for info, I was not aware of recent changes in `thangngoc89/bs-ant-design`.
I don't plan to contribute to it though as it has different design decisions.
I will focus on improving `zpnester/bs-antd` for now.
